name: HAPPY Online Marketing
favicon: null
layout_spectrum: 0.24889
typography_spectrum: 0.39327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ececeb'
    - '#ff4647'
    - '#dc0000'
    - '#f78787'
    - '#f3abab'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
